### ISSUE TITLE
Failed to update metadata after import

### ISSUE THREAD

**Issue by JetsonFlyers** [willmiao/ComfyUI-Lora-Manager#565]
### **LoRA Manager Version**
- Version: `v0.9.7`

### **Environment Information**
- **Operating System**: Windows 11
- **Browser & Version**: Firefox 143.0.4 (64-bit) (also Brave 1.83.112 Chromium 141.0.7390.70)

### **Issue Description**
- Imported images do not appear in Manager. Terminal shows error. Image does appear in folder.

### **Steps to Reproduce**
1. Open LoRA Manager in Firefox (or Brave).
2. Open (any) Lora info. Drag and drop an image to "Drag & drop images or videos here"
3. Notification says "Example images imported successfully" but image does not appear in window or show on Lora Card (for new lora).
4. Same behavior even with adding by selecting file.

### **Expected Behavior**
- Imported image displays and can be selected as default image.

### **Screenshots** *(If applicable)*
- Upload screenshots or screen recordings.

### **Logs**
-  AttributeError: 'NoneType' object has no attribute 'get'
Failed to update metadata after import: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Users\*****\ComfyUI\custom_nodes\comfyui-lora-manager\py\utils\example_images_metadata.py", line 274, in update_metadata_after_import
    custom_images = civitai_data.get('customImages')
                    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

### **Additional Context** *(Optional)*
- Happened immediately after update to 0.9.7
